### PR TITLE
POST-175: improved error handling and logging in FetchEvents.

### PR DESCRIPTION
**Pull request by henrikoppen**
JIRA: https://jira.vipps.io/browse/POST-175

### CODE REVIEW

**Comment by mats-vipps** [comment]
Seems good 😄 Could you write a test for this case as well?

**Review by mats-vipps — CHANGES_REQUESTED** [review]
Great! But I would love it if you would add a test-case for this as well. Just to check that all the casting works 😄

**Comment by dtitov** [comment]
LGTM.

**Review by mats-vipps — APPROVED** [review]
nice work! 😃

**Pull request merged**
